version: '3.1'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: ${ES_NAME}
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"